import{a as h,S as P,i as n}from"./assets/vendor-DaKTFKe4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="56206542-d30ce4b763db5e6ca8fe7f09b";h.defaults.baseURL="https://pixabay.com/api/";async function g(t,r){const i={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await h.get("",{params:i})).data}const u=document.querySelector(".gallery"),l=document.querySelector("#loader"),d=document.querySelector(".load-more"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const r=t.map(({webformatURL:i,largeImageURL:a,tags:e,likes:o,views:s,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${i}" alt="${e}" />
          <div class="info">
            <p class="info-item"><b>Likes</b>${o}</p>
            <p class="info-item"><b>Views</b>${s}</p>
            <p class="info-item"><b>Comments</b>${S}</p>
            <p class="info-item"><b>Downloads</b>${v}</p>
          </div>
        </a>
      </li>
    `).join("");u.insertAdjacentHTML("beforeend",r),E.refresh()}function M(){u&&(u.innerHTML="")}function y(){l&&l.classList.add("is-active")}function b(){l&&l.classList.remove("is-active")}function L(){d&&d.classList.remove("is-hidden")}function f(){d&&d.classList.add("is-hidden")}const $=document.querySelector(".form"),B=document.querySelector(".load-more");let m="",c=1;const w=15;$.addEventListener("submit",R);B.addEventListener("click",O);async function R(t){t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r===""){n.warning({title:"Caution",message:"Please enter a keyword to search!",position:"topRight"});return}m=r,c=1,M(),f(),y();try{const i=await g(m,c);if(!i.hits||i.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(i.hits),i.totalHits>w&&L()}catch(i){console.error(i),n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{b(),t.target.reset()}}async function O(){c+=1,f(),y();try{const t=await g(m,c);p(t.hits),L(),x();const r=Math.ceil(t.totalHits/w);c>=r&&(f(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),n.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}finally{b()}}function x(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
