import{a as m,S as P,i}from"./assets/vendor-DaKTFKe4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="56206542-d30ce4b763db5e6ca8fe7f09b";m.defaults.baseURL="https://pixabay.com/api/";async function h(t,r){const s={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await m.get("",{params:s})).data}const u=document.querySelector(".gallery"),l=document.querySelector("#loader"),d=document.querySelector(".load-more"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" />
          <div class="info">
            <p class="info-item"><b>Likes</b>${o}</p>
            <p class="info-item"><b>Views</b>${n}</p>
            <p class="info-item"><b>Comments</b>${v}</p>
            <p class="info-item"><b>Downloads</b>${S}</p>
          </div>
        </a>
      </li>
    `).join("");u.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){u&&(u.innerHTML="")}function p(){l&&l.classList.add("is-active")}function y(){l&&l.classList.remove("is-active")}function b(){d&&d.classList.remove("is-hidden")}function L(){d&&d.classList.add("is-hidden")}const R=document.querySelector(".form"),$=document.querySelector(".load-more");let f="",c=1;const w=15;R.addEventListener("submit",B);$.addEventListener("click",O);async function B(t){t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r===""){i.warning({title:"Caution",message:"Please enter a keyword to search!",position:"topRight"});return}f=r,c=1,M(),L(),p();try{const s=await h(f,c);if(!s.hits||s.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),s.totalHits>w?b():i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){console.error(s),i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{y(),t.target.reset()}}async function O(){c+=1,L(),p();try{const t=await h(f,c);g(t.hits),x();const r=Math.ceil(t.totalHits/w);c<r?b():i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error(t),i.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}finally{y()}}function x(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
